* Ver. 20190721 
1. 精简版贴进整合版
* 整合版
** 第一步：抉择
*** 使用自由意志。想清楚真正想要什麽，然后行动。是跟著控制编程走，还是听从内心指引。
*** 让自己独处，思考这一生想要什麽，了解自己想要显化什麽。一定要对自己诚实，不要欺骗自己。缺乏诚实会造成恐惧。
*** 保持觉知去观察我们是如何以及因何作出那些选择的。
*** 抉择的过程，就是整合不同面向的自我、去除迷惑的过程，将所有的面向整合为一。
*** 当很清楚自己想要什麽的时候，抉择才会明确。抉择要尽可能的精确、明确、具体。深入想要的细节。
*** 不管是遇到了什麽阻碍，不管别人怎麽说，坚持再坚持，绝对不要放弃。显化需要时间。
*** 人是无极限的，可以显化任何的东西。把“我不能”改成“我怎么才能（显化）”。
** 第二步：祈请
*** 使用情感、想象和可视化来填充能量流。
*** 使用情绪的力量。用所有热心渴望来吸引我们的抉择，用情绪吸引帮助显化的各种人事物。
*** 可以祈请、祷告、冥想、观想或假装看到了要显化的目标。
*** 可以用情绪呼请光明势力帮助自己想显化的事物，呼请圣哲曼的临在，呼请天使、呼请龙族、呼请抵抗运动、呼请扬升大师们，只要愿意呼请他们，他们就会帮助我们显化。
*** 只要抓到各种精确细节就放到自己情绪和观想画面裡。有了明确的画面就可以关注那个画面，但不要变成迷恋和痴迷。人生需要继续前行，不是因为祈请是显化法则的一部份，所以就一直的观想成天在观想；也不是说这是显化法则的一部份就踟蹰不前。把抉择愿望先放心裡然后过好每一天，我们需要不断的反覆使用显化法则直到我们想要的东西显化的那一天。
** 第三步：行动
*** 制定一个目标，朝那目标前进。如果不拿出具体的行动，什麽事情也不会发生。
*** 具体行动不代表我们要拚死拚活的努力工作、做很辛苦的事情或勉强自己，而是顺应内在的指引，做自己该做的事情。
*** 具体行动是一个投入热情而且按部就班的行动，只要用正确方法来做的话，具体行动上可以非常轻鬆和顺利。
*** 按照指引或灵感，带着显化目标已经实现的体验去行动。
** Decision-Pray-Action-Loop:DPAL
*** 说要一个新房子。我得决定买一个新房子，然后上网找房子把房子模样刻印在脑海裡。然后拿出具体行动；找到新工作有更好的收入。接著就是祈请光明势力来帮助自己，接著问朋友有没有适合的房子，就这样不断地重複一直重複最后换到自己理想的房子。
** 实相塑造法
*** 有意识的专注在自己显化的事物上。专注包括看、想、听、触摸等。
*** 精确地专注可以精确地显化。
*** 可以专注在实物，也可以专注在模型。
*** 关注、感激并拓展生活中对自己有用的东西或东西有用的部分。
*** 专注在更好的人事物上面。
*** 听从内在的指引，走出舒适圈，花时间拓展眼界，才有更好的目标可以显化。
*** 克服恐惧，对干扰事物进行实相过滤法。
*** 要有意愿通过物理的经验（不带评判地）周遭和内在增强的能量场域来扩展它.
*** 使用实相塑造法，可以同时显化多个目标。
** 彩虹漩涡支持场
*** 我是临在会形成一个可以扩及整个地球的漩涡支持场。这个漩涡支持场可以吸引所有你要抉择要显化的人事物。
*** 在纸板上面描绘代表完美的人生的画面。可以画画把你要的完美人生画在上面，也可以把杂志上代表完美人生的照片剪下来贴上去。把觉得漂亮美好的图都剪下来，我们要用这个心灵地图和漩涡加持场加速显化你的完美人生。
*** 冥想、观想或者睁眼想象，身边有个水平的彩虹漩涡。彩虹漩涡将你心灵地图上面的人事物吸进你的生活；吸进你的身体。彩虹漩涡的旋转方向没关係，逆时针或者顺时针都可以，将心灵地图上面的人事物吸引到你的生活裡面。
** 实相过滤法
*** 显化逆转法就是一个抉择：不论在任何场合，你再也不会接受某一类人事物出现在你的人生中。
*** 强调“拒绝”，而不是专注在需要被否定的事物上。
*** 显化逆转法也需要点时间，对每一个错误的人事物说”不”和”拒绝”都是一小步的胜利。
*** 可以逆转过去显化的东西。先从小事情开始逆转，生活周遭的环境开始过滤我们想要发生的实相。
** 补充：
*** 感谢是有意识的了解现况知道现在的情形。要感谢宇宙中显化给我们的恩典和人事物，但不要感谢负面的人事物。
*** 如果不在矩阵裡生活不去贷款当奴隶不给自己更多经济压力，显化会更快一些。
*** 不是每个人会同意你的自由意志，你可以决定什麽对你比较重要。
*** 高维存有不会内在天人交战。他们很清楚自己要什麽，他们心智体、肉体、情绪体是统合的，所以可以马上显化他们想要的。
*** 你要对自己诚实，要很清楚自己到底要什麽，要丰田还是宾士。因为你的抉择会吸引到可以帮助你显化宾士的人事物。
*** 显化金钱：我该显化多少钱？钱怎麽来？好比说我想要银行有10亿。自己要想银行帐户或手上现金有多少钱。
*** 显化金钱并不是我是临在的本意。我是临在会帮助你显化金钱，让你想做的事情。钱只是工具，重要的是你要钱来做什麽，比如你想要新车，那麽买车的钱就会过来。
* 修改版
  “显化，本身就是显化者与显化目标之间的相逢。”
** 显化
   显化，是指事物从无到有的过程。 举个简单的例子：
   假设我现在想要吃东西，而我面前什么都没有，就是所谓的“无”。我去超市买了一些食物。当食物在我面前出现，这就是“有”。我的食物在我面前经历了从“无”到“有”的过程，我完成了食物在我面前的显化。
   或许有人会问：“食物本来就做好了，放在超市，只是不在我面前而已。怎么能算从无到有？”
   应该这样理解：我完成的是食物在“我面前”的显化，而不是食物在“超市里”的显化。关键是“我面前”。食物在“我面前”从无到有，而不是在其他地方从无到有。
   或许有人会说：“食物一直躺在超市的货架上，是你走到超市拿起了它。应该说是你出现在食物面前，而不是食物出现在你面前。而你说是食物在你面前经历了从无到有的过程，这是不是不妥？”
   显化只关心终点，不在乎起点，也不在乎过程。最终食物出现在我面前，这就是我想要的结果，其它细节相对于这个结果来说，不重要。
   这也正是显化神奇的地方。我们只需要关心我们的显化目标，至于它在哪儿，如何出现，都是次要的。
** 显化法则
   显化法则，人们在显化事物的过程中，所需要遵循的规律，或称法则。按照这个法则，显化的速度会加快。
   显化法则具有如下三个步骤（这是最初版本）：
   “ 1、抉择。 我们必须如水晶般清晰并坚持我们想要的，不要摇摆不定。花点时间明确自己是值得的。
   2、意志/呼请。 呼请与意志涉及到使用我们的情感、想象和可视化来填充能量流，深入到我们想要的事物的细节。带着期待，但别沉迷于它，将其放下。然后无论如何，不放弃我们真心渴望的。
   3、行动。 行动就是根据你先前的抉择和呼请作出你被指引去做的行为，带着一种你渴望的已经显化的那股能量的体验去做，就像细胞语言一般。 ”
   为了更好地体现这三步的内容，这个三个步骤的名称依次被修改为：抉择、充能、显化。
   并增加一个步骤：重复。 
   于是，显化法则的内容如下：
   1、抉择：做出强力的肯定性决定，而不是愿望
   2、充能：使用想象、可视化、呼请（祈愿），在情感上付出热情与奉献，深入目标细节
   3、显化：根据灵感，带着目标已显化的感觉，做出务实的行动
   4、重复：不断重复上述过程

** 显化法则原理<暂时不写>
<小心原生异常带你绕圈。>

** 显化法则的使用<暂时不写>
<介绍黑暗势力如何误导大众，让大众使用显化法则对付大众自己>
   
** //2019-06-13补充：
   可以引入“能量条块”：
1. 填写充能事件可以为能量条充能，
2. 能量条中的能量随着时间而减少，
3. 翻看显化目标可以充能。
4. 当能量条为零时，显化过程搁置。
5. 当能量条充盈时，显化加速。
6. 能量条用来计量充能阶段投入的精力
7. 充能事件可以由用户自定义难度，或者自定义付出的精力。
8. 随着时间的流逝，如果没有阶段性产出，即灵感和行动，能量条的上限会降低，代表显化者的积极性再降低。此时需要重新评估抉择和积极性。

